"""initial schema

Revision ID: dcbfffecfce5
Revises: 
Create Date: 2026-04-01 16:30:48.047200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcbfffecfce5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_browser', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('include_speed_test', sa.Boolean(), nullable=False),
    sa.Column('include_ping_test', sa.Boolean(), nullable=False),
    sa.Column('include_dns_test', sa.Boolean(), nullable=False),
    sa.Column('include_wifi_scan', sa.Boolean(), nullable=False),
    sa.Column('include_traceroute', sa.Boolean(), nullable=False),
    sa.Column('include_device_scan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notified_browser', sa.Boolean(), nullable=False),
    sa.Column('notified_email', sa.Boolean(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['threshold_id'], ['alert_thresholds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_threshold_id'), ['threshold_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('device_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=True),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_scans_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_scans_timestamp'), ['timestamp'], unique=False)

    op.create_table('dns_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('target_domain', sa.String(length=255), nullable=False),
    sa.Column('resolution_time_ms', sa.Float(), nullable=False),
    sa.Column('resolved_ip', sa.String(length=45), nullable=True),
    sa.Column('dns_server', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dns_results_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dns_results_timestamp'), ['timestamp'], unique=False)

    op.create_table('ping_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('target_host', sa.String(length=255), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('min_latency_ms', sa.Float(), nullable=False),
    sa.Column('max_latency_ms', sa.Float(), nullable=False),
    sa.Column('jitter_ms', sa.Float(), nullable=False),
    sa.Column('packet_loss_pct', sa.Float(), nullable=False),
    sa.Column('packets_sent', sa.Integer(), nullable=False),
    sa.Column('packets_received', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ping_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ping_results_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ping_results_timestamp'), ['timestamp'], unique=False)

    op.create_table('speed_test_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('download_mbps', sa.Float(), nullable=False),
    sa.Column('upload_mbps', sa.Float(), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=True),
    sa.Column('server_host', sa.String(length=255), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speed_test_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speed_test_results_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_speed_test_results_timestamp'), ['timestamp'], unique=False)

    op.create_table('traceroute_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=False),
    sa.Column('target_host', sa.String(length=255), nullable=False),
    sa.Column('total_hops', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traceroute_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traceroute_results_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traceroute_results_timestamp'), ['timestamp'], unique=False)

    op.create_table('wifi_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('test_session_id', sa.Integer(), nullable=True),
    sa.Column('ssid', sa.String(length=255), nullable=True),
    sa.Column('bssid', sa.String(length=17), nullable=True),
    sa.Column('rssi_dbm', sa.Integer(), nullable=True),
    sa.Column('signal_pct', sa.Integer(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('band', sa.String(length=20), nullable=True),
    sa.Column('radio_type', sa.String(length=20), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('rx_rate_mbps', sa.Float(), nullable=True),
    sa.Column('tx_rate_mbps', sa.Float(), nullable=True),
    sa.Column('channel_utilization_pct', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wifi_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wifi_snapshots_test_session_id'), ['test_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wifi_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('discovered_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('entry_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['device_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('discovered_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discovered_devices_scan_id'), ['scan_id'], unique=False)

    op.create_table('traceroute_hops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('traceroute_id', sa.Integer(), nullable=False),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('rtt1_ms', sa.Float(), nullable=True),
    sa.Column('rtt2_ms', sa.Float(), nullable=True),
    sa.Column('rtt3_ms', sa.Float(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['traceroute_id'], ['traceroute_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traceroute_hops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traceroute_hops_traceroute_id'), ['traceroute_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traceroute_hops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traceroute_hops_traceroute_id'))

    op.drop_table('traceroute_hops')
    with op.batch_alter_table('discovered_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discovered_devices_scan_id'))

    op.drop_table('discovered_devices')
    with op.batch_alter_table('wifi_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wifi_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_wifi_snapshots_test_session_id'))

    op.drop_table('wifi_snapshots')
    with op.batch_alter_table('traceroute_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traceroute_results_timestamp'))
        batch_op.drop_index(batch_op.f('ix_traceroute_results_test_session_id'))

    op.drop_table('traceroute_results')
    with op.batch_alter_table('speed_test_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speed_test_results_timestamp'))
        batch_op.drop_index(batch_op.f('ix_speed_test_results_test_session_id'))

    op.drop_table('speed_test_results')
    with op.batch_alter_table('ping_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ping_results_timestamp'))
        batch_op.drop_index(batch_op.f('ix_ping_results_test_session_id'))

    op.drop_table('ping_results')
    with op.batch_alter_table('dns_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dns_results_timestamp'))
        batch_op.drop_index(batch_op.f('ix_dns_results_test_session_id'))

    op.drop_table('dns_results')
    with op.batch_alter_table('device_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_scans_timestamp'))
        batch_op.drop_index(batch_op.f('ix_device_scans_test_session_id'))

    op.drop_table('device_scans')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_threshold_id'))

    op.drop_table('alert_events')
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_sessions_started_at'))

    op.drop_table('test_sessions')
    op.drop_table('schedule_configs')
    op.drop_table('notification_settings')
    op.drop_table('alert_thresholds')
    # ### end Alembic commands ###
